spring.application.name=crintx

# Configuración del Servidor
server.port=8080
server.servlet.context-path=/

# Codificación y Formato JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Panama
spring.jackson.default-property-inclusion=non_null

# Configuración de Logging
logging.config=classpath:logback-spring.xml

# Configuración de MongoDB (AWS MongoDB Atlas / Local)
# Si no se define la variable de entorno MONGODB_URI, utiliza la base de datos 'crintx' por defecto
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/crintx}
spring.data.mongodb.auto-index-creation=true

