spring.application.name=crintx

# Configuración del Servidor
server.port=8080
server.servlet.context-path=/

# Codificación y Formato JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Panama
spring.jackson.default-property-inclusion=non_null

# Configuración de Logging
logging.config=classpath:logback-spring.xml

# Tipo de almacenamiento: 'in-memory' para pruebas locales instantáneas en Postman o 'mongodb' cuando se conecta a la BD
app.storage.type=${STORAGE_TYPE:in-memory}

# Desactivar auto-configuración de Mongo en modo in-memory para evitar timeouts
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
